server:
  port: 8085

spring:
  application:
    name: VEHICLE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_db
    username: postgres
    password: ayush
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: https://project-natal-2.onrender.com
