server:
  port: 8082

spring:
  application:
    name: DRIVER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: postgres
    password: ayush
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: driver_group
      auto-offset-reset: earliest


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.web: DEBUG       # Enables detailed logging for Spring Web requests
    org.springframework.security: DEBUG  # Enables detailed logging for Spring Security


