server:
  port: 8083

spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: ayush
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking_service_group
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

